web:
  env_file:
   - conf/development.env
  build: .
  command: python manage.py runserver 0.0.0.0:5001
  ports:
   - "5001:5001"
  volumes:
   - .:/code
  links:
   - redis
   - db
worker:
  env_file:
   - conf/development.env
  build: .
  command: celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
  volumes:
   - .:/code
  links:
   - redis
   - db
redis:
  image: redis
db:
  image: postgres